### ISSUE TITLE
Hover does not open documentation in the editor

### ISSUE THREAD

**Issue by VladimirMarko** [pine-vm/pine#12]
According to https://github.com/elm-fullstack/elm-fullstack/tree/main/implement/example-apps/elm-editor, the following functionality should exist in https://elm-editor.com/:

> Showing documentation and details when hovering the mouse cursor over a part of the code.

However, no such thing occurs.

In fact, I do not believe that there is any way to access documentation in the editor, except as part of a code suggestion.

**Comment by Viir** [comment]
Here is a video showing how the documentation tooltip looks like in practice:

![2021-11-14-elm-editor-hover-tips](https://user-images.githubusercontent.com/19209696/141691238-afffa5cc-7038-4d30-989d-47394cbf978d.gif)

If you found a case where it does not work as expected, let us know.

**Comment by VladimirMarko** [comment]
Thank you. You are correct - it does indeed work for many.

What confused me is that there is no documentation shown for the majority of the identifiers in the default "increment/decrement buttons" demo project that loads, when you visit the https://elm-editor.com/ website:

`Program`,
`Browser`,
`Browser.sandbox`,
`Html.Html`,
`Html.div`,
`Html.Attributes.style`,
`Html.Events.onClick`,
`Html.text`,
all have no documentation (on hover).

What's the type of `Html.text`? Well from context I can see that it is gonna be `String -> something`, but I see no way to get the editor to tell me what exactly it is.

**Comment by Viir** [comment]
> What confused me is that there is no documentation shown for the majority of the identifiers in the default "increment/decrement buttons" demo project that loads when you visit the https://elm-editor.com/ website:

Yes, I am sure we can find a better example project. One that is less confusing and better illustrates the available functionality.
The current default example project was just a quick sketch, nothing we need to keep.

**Comment by Viir** [comment]
This issue was fixed with https://github.com/pine-vm/pine/commit/e4949e0d1fdfe7eba8dd326f8429b8765276dc6e

![image](https://github.com/pine-vm/pine/assets/19209696/6dd5ae36-58bb-4627-9433-00b47b1702c0)
