### ISSUE TITLE
Client couldn't create connection to server

### ISSUE THREAD

**Issue by wolfadex** [pine-vm/pine#26]
When installing the plugin or starting vscode with it already installed I get:
```
[Error - 9:07:39 AM] Pine Language Server Client client: couldn't create connection to server.
Launching server using command pine failed. Error: spawn pine ENOENT
```

**Device:**
Apple M2 Max
macOS Sequoia 15.2

**VSCode:**
Version: 1.96.2 (Universal)
Commit: fabdb6a30b49f79a7aba0f2ad9df9b399473380f
Date: 2024-12-19T10:22:47.216Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0

**Comment by Viir** [comment]
That looks like registration of the `pine` executable file is not yet propagated into VS Code.

When running the command `pine  --version` from VS Code, it should show `pine 0.3.29`

![image](https://github.com/user-attachments/assets/30ae45e1-d4c6-4dc1-899d-4534410f479c)

Does running the command `pine  --version` work at all on that setup?

After you have downloaded the `pine` binary from <https://pine-vm.org/download> you can let it register the path by running the command `./pine  install`

![image](https://github.com/user-attachments/assets/99e0a0b5-f2ea-4f44-b87b-e8b0bf51e07c)

If its only missing in VS Code, I noticed sometimes I need to close all instances of VS Code before a changed environment variable is propagated.

**Comment by wolfadex** [comment]
After downloading Pine and running the install command it's working! Wasn't aware I had to separately install Pine, though I suppose that makes sense. I did miss the last step of the readme too
> Make sure you have Pine installed: https://pine-vm.org/download
